//! Elden Ring's open-world merchants, by NpcParam row, for the Minecraft side to replace with villagers.
//! Generated by tools/generate_merchants.py from the game's NpcParam and Paramdex's names; do not edit by hand.

/// Sorted NpcParam rows.
static MERCHANTS: &[i32] = &[
	32000000,
	32000010,
	32000012,
	32000020,
	32000030,
	32000032,
	32000034,
	32000035,
	32000110,
	32000120,
	32000134,
	32000135,
	32000210,
	32000220,
	32000234,
	32001010,
	32001110,
	32001210,
	32001310,
	32001412,
	32001520,
	32001612,
	32001720,
	32001820,
	32001933,
	32002030,
	32002132,
	32002240,
	32002340,
	32002542,
	32002650,
	32002764,
	32002860,
	32002968,
	32003010,
	32020000,
	32020035,
];

pub fn is_merchant(npc_param_id: i32) -> bool {
	MERCHANTS.binary_search(&npc_param_id).is_ok()
}

/// NpcParam rows (sorted) with a Minecraft shop on R: 1 Hewg's anvil, 2 Roderika's spawn eggs.
static SHOPS: &[(i32, u8)] = &[
	(34510100, 1),
	(34510179, 1),
	(523200079, 2),
	(523200179, 2),
	(523200279, 2),
];

pub fn shop_at(npc_param_id: i32) -> u8 {
	SHOPS.binary_search_by_key(&npc_param_id, |s| s.0).map_or(0, |i| SHOPS[i].1)
}
