//! Elden Ring's open-world merchants, by NpcParam row, for the Minecraft side to replace with villagers.
//! Generated by tools/generate_merchants.py from Paramdex's ER NpcParam names; do not edit by hand.

/// Sorted NpcParam rows.
static MERCHANTS: &[i32] = &[
	32000000,
	32000010,
	32000012,
	32000020,
	32000030,
	32000032,
	32000034,
	32000035,
	32000110,
	32000120,
	32000134,
	32000135,
	32000210,
	32000220,
	32000234,
	32001010,
	32001110,
	32001210,
	32001310,
	32001412,
	32001520,
	32001612,
	32001720,
	32001820,
	32001933,
	32002030,
	32002132,
	32002240,
	32002340,
	32002542,
	32002650,
	32002764,
	32002860,
	32002968,
	32003010,
	32008010,
	32008900,
	32009000,
	32009100,
	32009200,
	32009210,
	32009300,
	32009400,
	32009500,
	32009600,
	32009700,
	32009800,
	32009900,
	32009910,
	32020000,
	32020035,
];

pub fn is_merchant(npc_param_id: i32) -> bool {
	MERCHANTS.binary_search(&npc_param_id).is_ok()
}

/// Hewg's NpcParam rows: the smith whose upgrade tab R replaces with Minecraft's anvil.
static SMITHS: &[i32] = &[
	34510100,
	34510179,
];

pub fn is_smith(npc_param_id: i32) -> bool {
	SMITHS.binary_search(&npc_param_id).is_ok()
}
