#!/usr/bin/env python3
"""Minecraft-style art for the Elden Ring items (no game assets).

Every icon is 16x16 in two layers: a grey "tint" layer that Minecraft colours per item (the item's
custom_model_data colour, picked from its name or infusion by tools/generate_items.py) and a fixed
layer on top (outlines, handles, gold fittings). Weapons are drawn along the diagonal like Minecraft's
tools; the rest come from pixel masks. Also writes the item model definitions, the models and the
worn armour textures (dyeable, so each set takes its own colour).
"""
import json
import math
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "fabric/src/main/resources/assets/eldencraft"

# Palette codes: tint shades (coloured per item) and fixed colours.
TINT = {"-": 92, "+": 150, "*": 214, "~": 120}
FIXED = {"#": (28, 24, 22), "h": (102, 70, 42), "H": (66, 44, 26), "g": (214, 170, 62), "G": (150, 112, 36),
         "w": (240, 236, 220), "r": (170, 36, 36), "b": (60, 110, 210), "s": (120, 120, 128), "S": (78, 78, 86),
         "l": (238, 214, 140), "p": (130, 70, 170)}


def blank():
    return [["." for _ in range(16)] for _ in range(16)]


def put(grid, x, y, c):
    if 0 <= x < 16 and 0 <= y < 16:
        grid[y][x] = c


def outline(grid):
    """Black edge around everything drawn, like Minecraft's item sprites."""
    out = [row[:] for row in grid]
    for y in range(16):
        for x in range(16):
            if grid[y][x] != ".":
                continue
            for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                nx, ny = x + dx, y + dy
                if 0 <= nx < 16 and 0 <= ny < 16 and grid[ny][nx] not in (".", "#"):
                    out[y][x] = "#"
                    break
    return out


# ---- weapons along the diagonal --------------------------------------------------------------------
# Each pixel has d, how far along the diagonal from the pommel (bottom left, 0) to the tip (top right, 15), and o,
# how far across it (negative toward the top left). A solid blade is a band of d and o.

def region(grid, test, code, shade=False, half=1.0):
    for y in range(16):
        for x in range(16):
            d, o = (x + 15 - y) / 2, (x - 15 + y) / 2
            hit = test(d, o)
            if hit is None or hit is False:
                continue
            c = code
            if shade and code == "+":
                off = hit if isinstance(hit, float) else o
                c = "*" if off < -half / 3 else "-" if off > half / 3 else "+"
            put(grid, x, y, c)


def diag(grid, d0, d1, half, code, shade=True, curve=0.0, taper=0.0):
    """A bar from d0 to d1, half as wide as {@code half} across; curve bends it toward the top left near the tip."""
    def test(d, o):
        if not d0 <= d <= d1:
            return None
        t = (d - d0) / max(0.5, d1 - d0)
        centre = -curve * t * t
        width = half * (1 - taper * t)
        off = o - centre
        return float(off) if abs(off) <= width + 1e-6 else None
    region(grid, test, code, shade, max(half, 0.5))


def cross(grid, d, half, code):
    """A bar across the diagonal at d (a crossguard)."""
    region(grid, lambda dd, o: abs(dd - d) <= 0.5 and abs(o) <= half, code)


def tip(grid, d, code="+"):
    region(grid, lambda dd, o: abs(dd - d) <= 0.5 and abs(o) <= 0, code)


def weapon(kind):
    g = blank()
    k = kind
    if k in ("dagger", "throwing"):
        diag(g, 1, 4.5, 0, "h"); cross(g, 5, 1, "g"); diag(g, 5.5, 11, 0.5, "+", taper=0.6)
    elif k in ("straight_sword", "light_greatsword"):
        diag(g, 0, 0.5, 0, "g"); diag(g, 1, 3.5, 0, "h"); cross(g, 4, 1.5, "g"); diag(g, 4.5, 14, 0.5, "+"); tip(g, 14.5)
    elif k == "greatsword":
        diag(g, 0, 2.5, 0, "h"); cross(g, 3, 2, "g"); diag(g, 3.5, 14, 1, "+"); tip(g, 14.5)
    elif k == "colossal_sword":
        diag(g, 0, 2.5, 0, "h"); cross(g, 3, 2.5, "S"); diag(g, 3.5, 14.5, 1.5, "+", taper=0.3)
    elif k in ("curved_sword", "backhand_blade"):
        diag(g, 0, 3.5, 0, "h"); cross(g, 4, 1, "g"); diag(g, 4.5, 13.5, 0.5, "+", curve=2.0, taper=0.4)
    elif k == "curved_greatsword":
        diag(g, 0, 2.5, 0, "h"); cross(g, 3, 1.5, "g"); diag(g, 3.5, 14, 1, "+", curve=2.5, taper=0.3)
    elif k in ("katana", "great_katana"):
        diag(g, 0, 4.5, 0, "H"); cross(g, 5, 1, "g")
        diag(g, 5.5, 14.5, 0 if k == "katana" else 0.5, "+", curve=1.0)
    elif k == "twinblade":
        diag(g, 0, 5.5, 0.5, "+", taper=0); diag(g, 6, 9, 0, "h"); cross(g, 6, 1, "g"); cross(g, 9, 1, "g"); diag(g, 9.5, 15, 0.5, "+")
    elif k in ("thrusting_sword", "heavy_thrusting_sword"):
        diag(g, 0, 3.5, 0, "h"); cross(g, 4, 1.5, "g"); diag(g, 4.5, 15, 0 if k == "thrusting_sword" else 0.5, "+", taper=0.5)
    elif k in ("axe", "greataxe"):
        diag(g, 0, 14, 0, "h")
        big = k == "greataxe"
        region(g, lambda d, o: 9 <= d <= 14 and -((3.5 if big else 2.5) - abs(d - 11.5) * 0.6) <= o <= -0.5, "+")
        if big:
            region(g, lambda d, o: 10 <= d <= 13.5 and 0.5 <= o <= 2 - abs(d - 11.75) * 0.6, "+")
        region(g, lambda d, o: 9.5 <= d <= 13.5 and abs(o + (3.5 if big else 2.5) - 0.0) <= 0.5 - 0, "*")
    elif k in ("hammer", "great_hammer", "colossal_weapon"):
        diag(g, 0, 12, 0 if k != "colossal_weapon" else 0.5, "h")
        size = 1.5 if k == "hammer" else 2.5
        region(g, lambda d, o: (11.5 if k == "hammer" else 10.5) <= d <= 15 and abs(o) <= size, "+", True, size)
    elif k == "flail":
        diag(g, 0, 6, 0, "h"); diag(g, 6.5, 10, 0, "s", shade=False)
        region(g, lambda d, o: (d - 12.5) ** 2 + (o + 0.5) ** 2 <= 3.2, "+", True, 1.5)
    elif k in ("spear", "great_spear"):
        diag(g, 0, 11.5, 0, "h"); cross(g, 11.5, 1 if k == "spear" else 1.5, "g")
        diag(g, 12, 15, 0.5 if k == "spear" else 1, "+", taper=0.8)
    elif k == "halberd":
        diag(g, 0, 15, 0, "h"); diag(g, 13, 15, 0.5, "+", taper=0.8)
        region(g, lambda d, o: 9.5 <= d <= 13 and -3 <= o <= -0.5, "+", True, 1.5)
        region(g, lambda d, o: 10.5 <= d <= 12 and 0.5 <= o <= 1.5, "+")
    elif k == "reaper":
        diag(g, 0, 13, 0, "h")
        for x in range(3, 13):
            y = 2 + (12 - x) * (12 - x) // 14
            put(g, x, y, "*" if x > 9 else "+")
            put(g, x, y + 1, "-" if x > 4 else ".")
    elif k == "whip":
        pts = [(2, 14), (3, 13), (4, 12), (5, 11), (6, 10), (7, 9), (8, 9), (9, 8), (10, 8), (11, 7), (12, 6), (12, 5), (13, 4), (13, 3), (14, 2)]
        for i, (x, y) in enumerate(pts):
            put(g, x, y, "h" if i < 4 else "+")
    elif k in ("fist", "claw"):
        for y in range(5, 13):
            for x in range(4, 12):
                if (x - 7.5) ** 2 / 16 + (y - 9) ** 2 / 20 <= 1:
                    put(g, x, y, "+" if y > 6 else "*")
        if k == "claw":
            for x in (5, 8, 11):
                for i in range(4):
                    put(g, x + i // 2, 4 - i, "*")
    elif k in ("light_bow", "bow", "greatbow"):
        r = {"light_bow": 9, "bow": 11, "greatbow": 13}[k]
        bulge = 2.5 if k != "greatbow" else 3.5
        lo = (15 - r) / 2
        region(g, lambda d, o: lo <= d <= 15 - lo and abs(o + bulge * math.sin(math.pi * (d - lo) / (15 - 2 * lo))) <= 0.5, "+")
        region(g, lambda d, o: lo <= d <= 15 - lo and abs(o) <= 0, "w")
        cross(g, 7.5, 0, "h")
    elif k in ("crossbow", "ballista"):
        diag(g, 1, 12, 0, "h")
        region(g, lambda d, o: abs(d - (10 - abs(o) * 0.4)) <= 0.5 and abs(o) <= (4 if k == "crossbow" else 5), "+")
        cross(g, 11, 0.5, "s")
    elif k == "staff":
        diag(g, 0, 11.5, 0, "h")
        region(g, lambda d, o: (d - 13) ** 2 + o ** 2 <= 2.3, "+", True, 1)
        region(g, lambda d, o: (d - 13) ** 2 + (o + 0.5) ** 2 <= 0.3, "*")
    elif k == "seal":
        for y in range(2, 14):
            for x in range(2, 14):
                dist = math.hypot(x - 7.5, y - 7.5)
                if dist <= 5.8:
                    put(g, x, y, "+" if dist > 4 else "-")
        for x, y in ((7, 5), (8, 5), (7, 6), (8, 6), (6, 8), (9, 8), (7, 9), (8, 9), (7, 10), (8, 10)):
            put(g, x, y, "*")
    elif k in ("small_shield", "medium_shield", "greatshield", "thrusting_shield"):
        w, top, bottom = {"small_shield": (4, 3, 12), "medium_shield": (5, 2, 14), "greatshield": (6, 1, 15), "thrusting_shield": (4, 2, 14)}[k]
        for y in range(top, bottom + 1):
            half = w if k != "small_shield" else round(math.sqrt(max(0, 4.5 ** 2 - (y - 7.5) ** 2)))
            if k == "medium_shield" and y > 9:
                half = max(0, w - (y - 9))
            for x in range(8 - half, 8 + half):
                put(g, x, y, "+" if x not in (8 - half, 7 + half) else "-")
        for y in range(top + 1, bottom):
            if g[y][7] != ".":
                put(g, 7, y, "g")
        if k == "thrusting_shield":
            diag(g, 12, 15, 0, "s", shade=False)
    elif k in ("arrow", "greatarrow", "bolt", "greatbolt"):
        diag(g, 1, 12.5, 0, "h")
        region(g, lambda d, o: 1 <= d <= 3 and 0.5 <= abs(o) <= 1, "w")
        diag(g, 12.5, 15, 1 if k in ("greatarrow", "greatbolt") else 0.5, "+", taper=0.9)
    elif k == "torch":
        diag(g, 0, 10.5, 0, "h")
        for dx, dy, c in ((11, 3, "g"), (12, 3, "r"), (11, 2, "r"), (12, 2, "g"), (12, 1, "l"), (13, 2, "l")):
            put(g, dx, dy, c)
    elif k == "perfume_bottle":
        for y in range(6, 14):
            for x in range(4, 12):
                if (x - 7.5) ** 2 / 14 + (y - 10) ** 2 / 14 <= 1:
                    put(g, x, y, "+")
        for y in range(3, 6):
            put(g, 7, y, "s"); put(g, 8, y, "s")
    else:
        diag(g, 1, 13, 0.5, "+")
    return outline(g)


# ---- masks for armour, talismans and goods -----------------------------------------------------

MASKS = {
    "helm_light": """
................
................
.....######.....
....#++++++#....
...#+******+#...
...#+++++++++#..
...#++++++++#...
...#+#####++#...
...#+#....#+#...
...##......##...
................
................""",
    "helm_medium": """
................
.....######.....
....#++++++#....
...#+******+#...
...#++++++++#...
...#++####++#...
...#+#....#+#...
...#+#....#+#...
...#++#..#++#...
....##....##....
................""",
    "helm_heavy": """
................
......####......
....##++++##....
...#+******+#...
...#++++++++#...
...#+######+#...
...#+#-#-#-+#...
...#+#####++#...
...#++++++++#...
....#++++++#....
.....######.....""",
    "chest_light": """
................
..###......###..
.#+++#....#+++#.
.#+*++####++*+#.
.#++++++++++++#.
..##+**++**+##..
...#++++++++#...
...#++++++++#...
...#++++++++#...
...#+-+-+-+-#...
...##########...""",
    "chest_medium": """
................
..###......###..
.#+++######+++#.
.#+**++++++**+#.
.#++++gggg++++#.
..##+++gg+++##..
...#++++++++#...
...#++++++++#...
...#++-++-++#...
...#++++++++#...
...##########...""",
    "chest_heavy": """
.###........###.
#+++#......#+++#
#+*++######++*+#
#++++++++++++++#
.##++*****+++##.
..#+++++++++++#.
..#++######+++#.
..#+++++++++++#.
..#++######+++#.
..#+++++++++++#.
..#############.""",
    "gauntlets_light": """
................
................
..####....####..
.#++++#..#++++#.
.#+**+#..#+**+#.
.#++++#..#++++#.
.#++++#..#++++#.
#++++++##++++++#
#+#+#+##+#+#+#+#
.##.#.#..#.#.##.
................""",
    "gauntlets_medium": """
................
..####....####..
.#++++#..#++++#.
.#+**+#..#+**+#.
.#gggg#..#gggg#.
.#++++#..#++++#.
#++++++##++++++#
#++++++##++++++#
#+#+#+##+#+#+#+#
.##.#.#..#.#.##.
................""",
    "gauntlets_heavy": """
................
.######..######.
#++++++##++++++#
#+****+##+****+#
#++++++##++++++#
#+----+##+----+#
#++++++##++++++#
#++++++##++++++#
#+#+#+#..#+#+#+#
.#.#.#....#.#.#.
................""",
    "legs_light": """
................
...##########...
...#++++++++#...
...#+**++**+#...
...#+++##+++#...
...#+++##+++#...
...#+++##+++#...
...#+++##+++#...
...#++#..#++#...
..#+++#..#+++#..
..#####..#####..""",
    "legs_medium": """
................
...##########...
...#++++++++#...
...#gggggggg#...
...#+**##**+#...
...#+++##+++#...
...#+-+##+-+#...
...#+++##+++#...
...#+++##+++#...
..#++++##++++#..
..#####..#####..""",
    "legs_heavy": """
...##########...
..#++++++++++#..
..#++******++#..
..#++++##++++#..
..#+-++##++-+#..
..#++++##++++#..
..#+**+##+**+#..
..#++++##++++#..
..#+-++##++-+#..
.#+++++##+++++#.
.######..######.""",
    "talisman": """
................
......####......
.....#....#.....
.....#....#.....
......#..#......
.....######.....
....#++++++#....
...#+******+#...
...#+*+--+*+#...
...#+*-gg-*+#...
...#+*-gg-*+#...
...#+*+--+*+#...
...#+******+#...
....#++++++#....
.....######.....""",
    "flask_crimson": """
......####......
......#ss#......
......#ss#......
.....##ss##.....
....#wrrrrw#....
...#rrrrrrrr#...
...#rrrlrrrr#...
...#rrrrrrrr#...
...#rrrrrrrr#...
....#rrrrrr#....
.....######.....""",
    "flask_cerulean": """
......####......
......#ss#......
......#ss#......
.....##ss##.....
....#wbbbbw#....
...#bbbbbbbb#...
...#bbbwbbbb#...
...#bbbbbbbb#...
...#bbbbbbbb#...
....#bbbbbb#....
.....######.....""",
    "physick": """
......####......
......#gg#......
.....##gg##.....
....#gwwwwg#....
...#gw****wg#...
...#w******w#...
...#w**++**w#...
...#w******w#...
...#gw****wg#...
....#gwwwwg#....
.....######.....""",
    "crystal_tear": """
................
.......##.......
......#*+#......
......#*+#......
.....#**++#.....
.....#*+++#.....
....#**+++-#....
....#*++++-#....
....#*+++--#....
.....#++--#.....
......####......""",
    "pot": """
................
.....######.....
....#hhhhhh#....
.....#hhhh#.....
....#hhhhhh#....
...#hhhhhhhh#...
...#hh++++hh#...
...#hh++++hh#...
...#hhhhhhhh#...
....#hhhhhh#....
.....######.....""",
    "perfume_bottle": """
................
......####......
......#gg#......
.....#ssss#.....
....#++++++#....
...#+******+#...
...#+*++++*+#...
...#++++++++#...
....#++++++#....
.....######.....
................""",
    "throwing": """
................
............##..
...........#*#..
..........#*+#..
.........#*+#...
........#*+#....
.......#*+#.....
......##+#......
.....#hh#.......
....#hh#........
....###.........""",
    "key": """
................
...####.........
..#gGGg#........
..#G..G#........
..#gGGg#........
...#gg########..
....#gggggggggg#
.........#g#g#..
.........##.#...
................""",
    "key_item": """
................
.....######.....
....#++++++#....
...#+******+#...
...#+*++++*+#...
...#+*+gg+*+#...
...#+*++++*+#...
...#+******+#...
....#++++++#....
.....######.....
................""",
    "letter": """
................
..############..
..#wwwwwwwwww#..
..#wSSSSSSSSw#..
..#wwwwwwwwww#..
..#wSSSSSSSww#..
..#wwwwwwwwww#..
..#wSSSSSSSSw#..
..#wwwwwwrrww#..
..#wwwwwwrrww#..
..############..""",
    "map": """
................
.##############.
.#llllllllllll#.
.#ll++lllll+ll#.
.#l++++lll++ll#.
.#ll++lllll+ll#.
.#llll--llllll#.
.#lllll--lllrl#.
.#llllll--llll#.
.#llllllllllll#.
.##############.""",
    "cookbook": """
................
...##########...
..#hhhhhhhhhh#..
..#h++++++++h#..
..#h+wwwwww+h#..
..#h+w++++w+h#..
..#h+wwwwww+h#..
..#h++++++++h#..
..#hhhhhhhhhh#..
..#wwwwwwwwww#..
...##########...""",
    "bell_bearing": """
.......##.......
......#gg#......
.....##gg##.....
....#++++++#....
...#+******+#...
...#+******+#...
..#+********+#..
..#++++++++++#..
..############..
.......##.......
................""",
    "smithing_stone": """
................
................
.....######.....
....#******#....
...#*++++++-#...
..#*++++++++-#..
..#++++++++--#..
..#-++++++---#..
...#---------#..
....#########...
................""",
    "somber_stone": """
................
.......##.......
......#**#......
.....#*++-#.....
....#*++++-#....
...#*++++++-#...
....#-++++-#....
.....#-++-#.....
......#--#......
.......##.......
................""",
    "glovewort": """
................
.......##.......
......#**#......
.....#*++*#.....
....#*+gg+*#....
.....#*++*#.....
......#**#......
.......#h#......
.......#h#......
......#hhh#.....
................""",
    "golden_seed": """
................
.......##.......
......#gg#......
.....#glgG#.....
....#gllgGG#....
....#glggGG#....
....#gggGGG#....
.....#gGGG#.....
......#hh#......
.......##.......
................""",
    "sacred_tear": """
................
.......##.......
......#ww#......
......#ww#......
.....#wllw#.....
....#wllllw#....
....#wlggllw#...
....#wllllw#....
.....#wwww#.....
......####......
................""",
    "memory_stone": """
................
......####......
.....#bbbb#.....
....#bwbbbb#....
...#bbbbbbbb#...
...#bbbbbbbb#...
...#bbbbbbbb#...
....#bbbbbb#....
.....#bbbb#.....
......####......
................""",
    "pouch": """
................
......#..#......
.....#h##h#.....
....#hhhhhh#....
...#hhhhhhhh#...
...#hh++++hh#...
...#hhhhhhhh#...
...#hhhhhhhh#...
....#hhhhhh#....
.....######.....
................""",
    "great_rune": """
................
......####......
.....#gggg#.....
....#gg++gg#....
...#gg+**+gg#...
...#g+****+g#...
...#gg+**+gg#...
....#gg++gg#....
.....#gggg#.....
......####......
................""",
    "golden_rune": """
................
.......##.......
......#gg#......
.....#gllg#.....
....#gl..lg#....
...#gl....lg#...
....#gl..lg#....
.....#gllg#.....
......#gg#......
.......##.......
................""",
    "remembrance": """
................
......####......
....##****##....
...#*++++++*#...
...#*+gggg+*#...
...#*+g--g+*#...
...#*+gggg+*#...
...#*++++++*#...
....##****##....
......####......
................""",
    "spirit_ash": """
................
......####......
.....#wwww#.....
....#w++++w#....
.....#++++#.....
....#++++++#....
...#+******+#...
...#+******+#...
...#++++++++#...
....#++++++#....
.....######.....""",
    "sorcery": """
................
..##########....
..#llllllll#....
..#l++++++l#....
..#l+*bb*+l#....
..#l+b**b+l#....
..#l+*bb*+l#....
..#l++++++l#....
..#llllllll#....
..#hhhhhhhh#....
..##########....""",
    "incantation": """
................
..##########....
..#llllllll#....
..#l++++++l#....
..#l+*gg*+l#....
..#l+g**g+l#....
..#l+*gg*+l#....
..#l++++++l#....
..#llllllll#....
..#hhhhhhhh#....
..##########....""",
    "material_plant": """
................
.......##.......
......#++#......
.....#+**+#.....
....#+*++*+#....
....#++++++#....
.....#+--+#.....
......#hh#......
......#hh#......
.......##.......
................""",
    "material_animal": """
................
................
....######......
...#wwwwww#.....
...#w****w##....
..#w******ww#...
..#w**++***w#...
...#w*****w#....
....#wwwww#.....
.....#####......
................""",
    "material_mineral": """
................
................
......####......
.....#****#.....
....#*+++++#....
...#*++**++-#...
...#++++++--#...
....#+++---#....
.....######.....
................
................""",
    "finger": """
................
.......##.......
......#ww#......
......#ww#......
......#ww#......
......#ww#......
.....#wwww#.....
.....#w++w#.....
.....#wwww#.....
......####......
................""",
    "grease": """
................
......####......
......#hh#......
.....######.....
....#++++++#....
....#+****+#....
....#++++++#....
....#++++++#....
....#++++++#....
.....######.....
................""",
    "bolus": """
................
................
.....######.....
....#++++++#....
...#+**++++-#...
...#+*+++++-#...
...#++++++--#...
...#+++++---#...
....#------#....
.....######.....
................""",
    "food": """
................
................
....#####.......
...#++++*##.....
..#+*+++**+#....
..#++++++++#....
..#+++++++-#....
...#+++++--#....
....#-----#.....
.....#####......
................""",
    "whetblade": """
................
............##..
...........#*#..
..........#*-#..
.........#*-#...
........#*-#....
.......#*-#.....
......#*-#......
.....#gg#.......
....#gg#........
....###.........""",
    "ash_of_war": """
................
......####......
.....#wwww#.....
....#w****w#....
...#w*++++*w#...
...#w*+gg+*w#...
...#w*++++*w#...
....#w****w#....
.....#wwww#.....
......####......
................""",
    "material": """
................
................
......####......
.....#****#.....
....#*++++-#....
....#++++--#....
.....#----#.....
......####......
................
................
................""",
    "consumable": """
................
......####......
.....#wwww#.....
....#w++++w#....
....#++**++#....
....#++++++#....
....#++++++#....
....#+++++-#....
.....#----#.....
......####......
................""",
}


def mask(name):
    rows = [r for r in MASKS[name].strip("\n").split("\n")]
    g = blank()
    top = (16 - len(rows)) // 2
    for y, row in enumerate(rows):
        for x, c in enumerate(row[:16]):
            put(g, x, top + y, c)
    return g


def save(grid, path_base):
    tint = Image.new("RGBA", (16, 16), (0, 0, 0, 0))
    fixed = Image.new("RGBA", (16, 16), (0, 0, 0, 0))
    for y in range(16):
        for x in range(16):
            c = grid[y][x]
            if c in TINT:
                v = TINT[c]
                tint.putpixel((x, y), (v, v, v, 255))
            elif c in FIXED:
                fixed.putpixel((x, y), FIXED[c] + (255,))
    path_base.parent.mkdir(parents=True, exist_ok=True)
    tint.save(str(path_base) + "_tint.png")
    fixed.save(str(path_base) + ".png")


def model(group, name, handheld):
    tex = f"eldencraft:item/er/{group}/{name}"
    (ASSETS / "models/item/er" / group).mkdir(parents=True, exist_ok=True)
    (ASSETS / "models/item/er" / group / f"{name}.json").write_text(json.dumps({
        "parent": "minecraft:item/handheld" if handheld else "minecraft:item/generated",
        "textures": {"layer0": tex + "_tint", "layer1": tex}}, indent=2) + "\n")
    path = ASSETS / "items/er" / (f"{group}/{name}.json" if group != "." else f"{name}.json")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps({"model": {"type": "minecraft:model", "model": f"eldencraft:item/er/{group}/{name}",
        "tints": [{"type": "minecraft:custom_model_data", "index": 0, "default": -1}, {"type": "minecraft:constant", "value": -1}]}},
        indent=2) + "\n")


WEAPONS = ["dagger", "straight_sword", "greatsword", "colossal_sword", "curved_sword", "curved_greatsword", "katana", "twinblade",
           "thrusting_sword", "heavy_thrusting_sword", "axe", "greataxe", "hammer", "great_hammer", "flail", "spear", "great_spear",
           "halberd", "reaper", "fist", "claw", "whip", "colossal_weapon", "light_bow", "bow", "greatbow", "crossbow", "ballista",
           "staff", "seal", "small_shield", "medium_shield", "greatshield", "arrow", "greatarrow", "bolt", "greatbolt", "torch",
           "perfume_bottle", "thrusting_shield", "backhand_blade", "light_greatsword", "great_katana", "throwing"]
GOODS = ["flask_crimson", "flask_cerulean", "physick", "crystal_tear", "pot", "perfume_bottle", "throwing", "key", "key_item",
         "letter", "map", "cookbook", "bell_bearing", "smithing_stone", "somber_stone", "glovewort", "golden_seed", "sacred_tear",
         "memory_stone", "pouch", "great_rune", "golden_rune", "remembrance", "spirit_ash", "sorcery", "incantation",
         "material_plant", "material_animal", "material_mineral", "finger", "grease", "bolus", "food", "whetblade", "ash_of_war",
         "material", "consumable"]


def armour_texture(weight, leggings):
    """A 64x32 humanoid armour layer in greys (dyed per set): plates, trims and rivets by weight class."""
    img = Image.new("RGBA", (64, 32), (0, 0, 0, 0))
    base = {"light": 150, "medium": 170, "heavy": 190}[weight]

    def box(x, y, w, h, d, pattern):
        # Minecraft's box UV layout: top/bottom then the four sides.
        faces = [(x + d, y, w, d), (x + d + w, y, w, d), (x, y + d, d, h), (x + d, y + d, w, h), (x + d + w, y + d, d, h), (x + d + w + d, y + d, w, h)]
        for fx, fy, fw, fh in faces:
            for py in range(fh):
                for px in range(fw):
                    img.putpixel((fx + px, fy + py), pattern(px, py, fw, fh))

    def plate(px, py, w, h):
        v = base
        if px in (0, w - 1) or py in (0, h - 1):
            v -= 45
        elif weight == "heavy" and py % 4 == 0:
            v -= 25
        elif weight == "medium" and (px + py) % 6 == 0:
            v -= 18
        elif weight == "light" and py % 3 == 0:
            v -= 12
        if weight != "light" and px in (1, w - 2) and py in (1, h - 2):
            v = 235
        return (v, v, v, 255)

    if leggings:
        box(16, 16, 8, 12, 4, plate)       # body (waist)
        box(0, 16, 4, 12, 4, plate)        # legs
    else:
        box(0, 0, 8, 8, 8, plate)          # head
        box(16, 16, 8, 12, 4, plate)       # body
        box(40, 16, 4, 12, 4, plate)       # arms
        box(0, 16, 4, 12, 4, plate)        # legs (boots)
    return img


def main():
    for w in WEAPONS:
        save(weapon(w), ASSETS / "textures/item/er/weapon" / w)
        model("weapon", w, w not in ("small_shield", "medium_shield", "greatshield", "thrusting_shield", "seal", "fist", "claw",
                                     "perfume_bottle"))
    for slot in ("helm", "chest", "gauntlets", "legs"):
        for weight in ("light", "medium", "heavy"):
            save(mask(f"{slot}_{weight}"), ASSETS / "textures/item/er/armour" / f"{slot}_{weight}")
            model("armour", f"{slot}_{weight}", False)
    save(mask("talisman"), ASSETS / "textures/item/er/misc/talisman")
    model("misc", "talisman", False)
    for name in GOODS:
        save(mask(name) if name in MASKS else weapon(name), ASSETS / "textures/item/er/goods" / name)
        model("goods", name, False)
    for weight in ("light", "medium", "heavy"):
        for layer, leggings in (("humanoid", False), ("humanoid_leggings", True)):
            path = ASSETS / f"textures/entity/equipment/{layer}/er_{weight}.png"
            path.parent.mkdir(parents=True, exist_ok=True)
            armour_texture(weight, leggings).save(path)
        dyed = {"dyeable": {"color_when_undyed": -1}}
        (ASSETS / "equipment").mkdir(parents=True, exist_ok=True)
        (ASSETS / f"equipment/er_{weight}.json").write_text(json.dumps({"layers": {
            "humanoid": [{"texture": f"eldencraft:er_{weight}", **dyed}],
            "humanoid_leggings": [{"texture": f"eldencraft:er_{weight}", **dyed}]}}, indent=2) + "\n")
    (ASSETS / "equipment/er_hidden.json").write_text(json.dumps({"layers": {}}, indent=2) + "\n")
    # Plain fallback models for the registered items themselves (stacks always carry their own item_model).
    for item, art in (("er_weapon", "weapon/straight_sword"), ("er_bow", "weapon/bow"), ("er_crossbow", "weapon/crossbow"),
                      ("er_ammo", "weapon/arrow"), ("er_shield", "weapon/medium_shield"), ("er_catalyst", "weapon/staff"),
                      ("er_armour", "armour/chest_medium"), ("er_talisman", "misc/talisman"), ("er_goods", "goods/consumable"),
                      ("er_ash", "goods/ash_of_war")):
        (ASSETS / f"items/{item}.json").write_text(json.dumps({"model": {"type": "minecraft:model", "model": f"eldencraft:item/er/{art}",
            "tints": [{"type": "minecraft:constant", "value": -6710887}, {"type": "minecraft:constant", "value": -1}]}}, indent=2) + "\n")
    print(f"art: {len(WEAPONS)} weapon classes, 12 armour icons, {len(GOODS)} goods, 3 worn armour weights")


if __name__ == "__main__":
    main()
