#!/usr/bin/env python3
"""Regenerates game/src/merchants.rs (the NpcParam rows of Elden Ring's open-world merchants) and
fabric/src/main/resources/data/eldencraft/er/merchants.json (which shop lineup each one sells).

Usage: tools/generate_merchants.py [ELDEN RING folder]   (or set ELDEN_RING)

A row counts as a trading merchant when it is Kalé or drops a merchant's Bell Bearing (map item lots 119000-119090,
one per merchant, five apart). The Bell Bearing says which lineup it sells: 100525 + 25 per merchant, Kalé 100500.
Merchant-named rows without one (the non-trading merchant NPCs, NpcParam 32008xxx-32009xxx) are left alone.
"""
import json
import os
from pathlib import Path
import re
import sys
import urllib.request

sys.path.insert(0, str(Path(__file__).resolve().parent))
import er_params  # noqa: E402

URL = "https://raw.githubusercontent.com/soulsmods/Paramdex/master/ER/Names/NpcParam.txt"
OUT = Path(__file__).resolve().parents[1] / "game/src/merchants.rs"
LINEUPS = Path(__file__).resolve().parents[1] / "fabric/src/main/resources/data/eldencraft/er/merchants.json"
DEFAULT_GAME = "/run/media/alex/a0da83cf-b021-4cfe-9104-edb6dd726a80/SteamLibrary/steamapps/common/ELDEN RING"
# Hewg and Iji are left as the real characters: they have quests, so they stay visible and are talked to with R.
NAME = re.compile(r"^(Merchant Kalé|Nomadic Merchant|Isolated Merchant|Hermit Merchant|Abandoned Merchant|Imprisoned Merchant|Merchant)(\s*\(.*\))?$")


def main():
    text = urllib.request.urlopen(URL, timeout=60).read().decode("utf-8")
    er_params.DEF_NAME["ItemLotParam_map"] = "ItemLotParam"
    reg = er_params.Regulation(sys.argv[1] if len(sys.argv) > 1 else os.environ.get("ELDEN_RING", DEFAULT_GAME))
    npcs = reg.rows("NpcParam")
    ids, lineups = [], {}
    for line in text.splitlines():
        row, _, name = line.partition(" ")
        if not (row.isdigit() and NAME.match(name.strip()) and "Donkey" not in name):
            continue
        npc = npcs.get(int(row))
        lot = npc["itemLotId_map"] if npc else -1
        if name.strip().startswith("Merchant Kal"):
            lineup = 100500
        elif 119000 <= lot <= 119090 and lot % 5 == 0:
            lineup = 100525 + 25 * ((lot - 119000) // 5)
        else:
            continue  # merchant-looking, but it never trades
        ids.append(int(row))
        lineups[int(row)] = lineup
    LINEUPS.write_text(json.dumps(lineups, separators=(",", ":")), encoding="utf-8")
    rows = "".join(f"\t{i},\n" for i in sorted(ids))
    shops = {1: [], 2: []}  # 1: Hewg's anvil, 2: Roderika's spawn eggs (R beside them; Shift+R talks natively)
    for line in text.splitlines():
        row, _, name = line.partition(" ")
        name = name.strip()
        if row.isdigit() and name.startswith("Smithing Master Hewg"):
            shops[1].append(int(row))
        elif row.isdigit() and name.startswith("Roderika"):
            shops[2].append(int(row))
    shop_rows = sorted((r, kind) for kind, rows in shops.items() for r in rows)
    shop_table = "".join(f"\t({r}, {kind}),\n" for r, kind in shop_rows)
    OUT.write_text("//! Elden Ring's open-world merchants, by NpcParam row, for the Minecraft side to replace with villagers.\n"
                   "//! Generated by tools/generate_merchants.py from the game's NpcParam and Paramdex's names; do not edit by hand.\n\n"
                   f"/// Sorted NpcParam rows.\nstatic MERCHANTS: &[i32] = &[\n{rows}];\n\n"
                   "pub fn is_merchant(npc_param_id: i32) -> bool {\n\tMERCHANTS.binary_search(&npc_param_id).is_ok()\n}\n\n"
                   "/// NpcParam rows (sorted) with a Minecraft shop on R: 1 Hewg's anvil, 2 Roderika's spawn eggs.\n"
                   f"static SHOPS: &[(i32, u8)] = &[\n{shop_table}];\n\n"
                   "pub fn shop_at(npc_param_id: i32) -> u8 {\n"
                   "\tSHOPS.binary_search_by_key(&npc_param_id, |s| s.0).map_or(0, |i| SHOPS[i].1)\n}\n", encoding="utf-8")
    print(f"{len(ids)} merchant rows -> {OUT}, {LINEUPS}")


if __name__ == "__main__":
    main()
