#!/usr/bin/env python3
"""Regenerates game/src/merchants.rs: the NpcParam rows of Elden Ring's open-world merchants.

Usage: tools/generate_merchants.py [NpcParam.txt]  (downloads Paramdex's ER/Names/NpcParam.txt when no file is given)
"""
from pathlib import Path
import re
import sys
import urllib.request

URL = "https://raw.githubusercontent.com/soulsmods/Paramdex/master/ER/Names/NpcParam.txt"
OUT = Path(__file__).resolve().parents[1] / "game/src/merchants.rs"
# Hewg and Iji are left as the real characters: they have quests, so they stay visible and are talked to with R.
NAME = re.compile(r"^(Merchant Kalé|Nomadic Merchant|Isolated Merchant|Hermit Merchant|Abandoned Merchant|Imprisoned Merchant|Merchant)(\s*\(.*\))?$")


def main():
    text = Path(sys.argv[1]).read_text(encoding="utf-8") if len(sys.argv) > 1 else urllib.request.urlopen(URL, timeout=60).read().decode("utf-8")
    ids = []
    for line in text.splitlines():
        row, _, name = line.partition(" ")
        if row.isdigit() and NAME.match(name.strip()) and "Donkey" not in name:
            ids.append(int(row))
    rows = "".join(f"\t{i},\n" for i in sorted(ids))
    OUT.write_text("//! Elden Ring's open-world merchants, by NpcParam row, for the Minecraft side to replace with villagers.\n"
                   "//! Generated by tools/generate_merchants.py from Paramdex's ER NpcParam names; do not edit by hand.\n\n"
                   f"/// Sorted NpcParam rows.\nstatic MERCHANTS: &[i32] = &[\n{rows}];\n\n"
                   "pub fn is_merchant(npc_param_id: i32) -> bool {\n\tMERCHANTS.binary_search(&npc_param_id).is_ok()\n}\n", encoding="utf-8")
    print(f"{len(ids)} merchant rows -> {OUT}")


if __name__ == "__main__":
    main()
